---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-cube
  namespace: logging
  labels:
    app: fluentd-cube
spec:
  selector:
    matchLabels:
      app: fluentd-cube
  template:
    metadata:
      labels:
        app: fluentd-cube
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd:v1.7-1
        env:
          - name: FLUENT_UID
            value: "0"
        securityContext:
          runAsUser: 0
          privileged: true
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlogtail
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: cube-fluentd-conf-volume
          mountPath: /fluentd/etc/
        - name: varcube
          mountPath: /var/cube

      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlogtail
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: cube-fluentd-conf-volume
        configMap:
          name: "cube-fluentd-conf"
      - name: varcube
        hostPath:
          path: /var/cube
      imagePullSecrets:
      - name: regcred