kind: pipeline
name: default

steps:
  - name: docker_build
    image: plugins/docker
    environment:
      TOKEN:
        from_secret: githubtoken
    settings:
      username: aakashsinghalmd01
      password: Welcome@md
      repo: cubeiocorp/cubews
      build_args_from_env:
      - TOKEN
      target: prod
      tags: ${DRONE_COMMIT}-${DRONE_BRANCH}
    resources:
      requests:
        cpu: 0.1
        memory: "1500Mi"
      limits:
        cpu: 1
        memory: "1500Mi"
    when:
      branch:
      - master
      - staging
      - develop
      event:
        exclude:
        - pull_request

  - name: docker_build_on_PR
    image: plugins/docker
    environment:
      TOKEN:
        from_secret: githubtoken
    settings:
      username: aakashsinghalmd01
      password: Welcome@md
      repo: cubeiocorp/cubews
      target: prod
      build_args_from_env:
      - TOKEN
      tags:
        - ${DRONE_COMMIT}-${DRONE_BRANCH}
        - ${DRONE_BRANCH}-latest
    resources:
      requests:
        cpu: 0.1
        memory: "1500Mi"
      limits:
        cpu: 1
        memory: "1500Mi"
    when:
      branch:
      - develop
      - staging
      - master
      event:
        include:
        - pull_request

  - name: Run_test_on_PR
    image: cubeiocorp/kubectl:latest
    pull: always
    commands:
    - cd /code && ./moviebooktest.sh
    when:
      branch:
      - develop
      - staging
      - master
      event:
        include:
        - pull_request

  - name: Run_event_path_test
    image: cubeiocorp/kubectl:latest
    pull: always
    commands:
    - cd /code && ./eventPathTest.sh
    when:
      branch:
      - develop
      - staging
      - master
      event:
        include:
        - pull_request
  - name: deploy_cubeServices_cube_dev
    image: quay.io/honestbee/drone-kubernetes
    settings:
      kubernetes_server: https://api-cluster-dev-k8s-local-uvhccq-328956788.us-east-1.elb.amazonaws.com
      kubernetes_token: eyJhbGciOiJSUzI1NiIsImtpZCI6IndMcEt2Und3TnBSNEF3c21TTWtVbGNmUzB6WU5aeFFYR1Q3V2dkdkF6WjgifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRyb25lLWRlcGxveS10b2tlbi05bDU4eCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJkcm9uZS1kZXBsb3kiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI2OGE4Nzg3OC1jMDI3LTRjODctYTE0ZS0yMGE2NDY3OTg1NTIiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVmYXVsdDpkcm9uZS1kZXBsb3kifQ.ZVPBdDezbbl_2Z2a6l8tbKsoOyPI3CDVWtStwl3ThXSvrhMlYsxaWP2I4PyIoRdVzIF0ubrBOoQbJ96QfFzAJ2SBPY40hGkl1AnQucipQrH-3bSlnzg8oIE1HjxoENc646AndApffQHs8ylFL96r0q5YZi6lWl8mOmdhT_mU4lCsz1rfU-hK9_5cT07UhC6iY5QXBi3NM7yteKOgFL9AsBHiI0SgpysePxw39VF68ivhUPoHRWLP5C1rS5IIrqVrv9GuVmC2m4LhQ0qp2dTW-WsbfJwIBlbaJ-ay8y-iBB9nv4F3fRfhkGrNKYjGaiwaGnykIpGVUnCSqcqV4rcSkA
      namespace: cube
      deployment: [ cubews-mock-v1, cubews-record-v1, cubews-replay-v1 ]
      repo: cubeiocorp/cubews
      container: cubews
      tag: ${DRONE_COMMIT}-${DRONE_BRANCH}
    when:
      branch:
      - develop
      event:
        exclude:
        - pull_request

  - name: deploy_cubeServices_cube_staging
    image: quay.io/honestbee/drone-kubernetes
    settings:
      kubernetes_server: https://api-cluster-prod-k8s-loca-4kne7o-1269526097.us-east-2.elb.amazonaws.com
      kubernetes_token: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4tNnF3ODgiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjU2ODJkNGQwLTk4YzctMTFlOS05ZTk5LTAyZWJkOThmMjllMiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmRlZmF1bHQifQ.VhuG5s3zodhV7p0UnXxmXL8TjnkT0blkBCog42RWiiMIzohZqoRe2v_RWhtb1kViRQ_8-0wV0NJqv3PLBn7YcigJwujApN2WfRFfeX8Iu_RCNJDrFJVAv_cgdyFltS04zFJ5NPZjwGDi2lKxvVdwcq5xmuS9ni5cw77AcCiKB2RHHz-dcfM66EjbexEFgDruBWPCR1nEl73bKgbtiqSQfXuMbWev7yNpRpMvhoP0Krt_F6BNZVOoOxIr7ZBzEkB5-vfvdnFU0l0Ye7aosGe7KXpRpEtdoE8tQF2t3hIFbZXCuH7a7cT7wswS65uDDBDlkoFxjZJu95qn7M5i0mOi5g
      namespace: cube
      deployment: [ cubews-mock-v1, cubews-record-v1, cubews-replay-v1 ]
      repo: cubeiocorp/cubews
      container: cubews
      tag: ${DRONE_COMMIT}-${DRONE_BRANCH}
    when:
      branch:
      - staging
      event:
        exclude:
        - pull_request

  - name: deploy_cubeServices_demo
    image: quay.io/honestbee/drone-kubernetes
    settings:
      kubernetes_server: https://api-cluster-prod-v2-k8s-l-iipk0l-2142764081.us-east-2.elb.amazonaws.com
      kubernetes_token: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4tOGo1eGsiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImJiMDQ5YmFmLWM4MTItMTFlOS1iNTRmLTBhN2UwYjg0ZjJjOCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmRlZmF1bHQifQ.gqbZfAl2ye-qcemLnb4r7G1_N5kR257LY2agGvTylYdFacMQzlAwKgAn50SFVAvNG5Vtbf7UYFEg53UcKLuMt1j5icP9H-VlbUySdTzuSDTlwyMur-O-ADILf7LBic2nD2g-xv5u0nSXpFzY0kIIp4X9U0ob5VyotHIvmThmnrLDZcl2znzeq0F423i4TyZYnLSLLS9Hxz44UUtKclmEzK4DAGoCmropR8HQkamtMGwNn26uoSCLVOlk-PHLv02x8vW7QNGS8iWwdEl2KkeIUdLV9y-0c8BnbZAKQtMdDuWqWHM4jDTiq9nXrd1SDjYCj2XsGn6grTjWUhqHlU-gqg
      namespace: cube
      deployment: [ cubews-mock-v1, cubews-record-v1, cubews-replay-v1 ]
      repo: cubeiocorp/cubews
      container: cubews
      tag: ${DRONE_COMMIT}-${DRONE_BRANCH}
    when:
      branch:
      - master
      event:
        exclude:
        - pull_request

  - name: notify
    image: drillster/drone-email
    settings:
      host: smtp.office365.com
      username:
        from_secret: EMAIL_USERNAME
      password:
        from_secret: EMAIL_PASSWORD
      from: email.sender@meshdynamics.io
      recipients: [ a80f6254.meshdynamics.io@amer.teams.ms, developers@meshdynamics.io ]
    when:
      status:
      - failure

trigger:
  branch:
  - master
  - staging
  - develop
