kind: pipeline
name: default

steps:
  - name: docker build
    image: plugins/docker
    settings:
      username: cubeiocorp
      password:
        from_secret: helloDocker1!
      repo: cubeiocorp/cubeui
      tags: test

trigger:
  branch:
  - master