apiVersion: v1
kind: Service
metadata:
  name: route-guide-service
  namespace: staging-as
  labels:
    app: route-guide
    component: route-server
spec:
  type: LoadBalancer
  ports:
  - port: 8980
    protocol: TCP
    targetPort: 8980
  selector:
    component: route-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: staging-as
spec:
  replicas: 1
  selector:
    matchLabels:
      component: route-server
  template:
    metadata:
      labels:
        app: route-guide
        component: route-server
        namespace: staging-as
    spec:
      containers:
      - name: route-guide
        image: cubeiocorp/grpc-route-guide-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8980
