apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJjdWJlaW9jb3JwIiwicGFzc3dvcmQiOiJTOXFlMmZKOCp2dGsiLCJlbWFpbCI6Iml0QGN1YmVjb3JwLmlvIiwiYXV0aCI6IlkzVmlaV2x2WTI5eWNEcFRPWEZsTW1aS09DcDJkR3M9In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson
