##################################################################################################
# Cube Web Services
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: cubews
  labels:
    app: cubews
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: cubews
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cubews-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cubews
        version: v1
    spec:
      containers:
      - name: cubews
        image: cubeiocorp/cubews:demo-1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred

##################################################################################################
# Cube UI
##################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: cubeui
  labels:
    app: cubeui
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: cubeui
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cubeui-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cubeui
        version: v1
    spec:
      containers:
      - name: cubeui
        image: cubeiocorp/cubeui:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
---
# TODO: the following exernalname didn't work for a service that didn't go through port 80
# apiVersion: v1
# kind: Service
# metadata:
#   name: aws-mysql-sakila
# spec:
#   type: ExternalName
#   externalName: sakila2.cnt3lftdrpew.us-west-2.rds.amazonaws.com

##################################################################################################
# Mysql data server in the mesh
##################################################################################################
# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql-sakila
#   labels:
#     app: mysql-sakila
# spec:
#   ports:
#   - port: 3306
#     name: tcp
#     protocol: TCP
#   selector:
#     app: mysql-sakila
# ---
# apiVersion: extensions/v1beta1
# kind: Deployment
# metadata:
#   name: mysql-sakila-v1
# spec:
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: mysql-sakila
#         version: v1
#     spec:
#       containers:
#       - name: mysql-sakila
#         image: cubeiocorp/mysql-sakila:v3
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 3306
# ---
##################################################################################################
# External mysql server and endpoint
##################################################################################################

# kind: Endpoints
# apiVersion: v1
# metadata:
#  name: aws-mysql-sakila
# subsets:
#  - addresses:
#      - ip: 54.69.153.210 #sakila2.cnt3lftdrpew.us-west-2.rds.amazonaws.com
#    ports:
#      - port: 3306
