apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: movieinfo
  namespace: {{namespace}}
  labels:
    app: moviebook
spec:
  hosts:
  - "{{namespace_host}}"
  gateways:
  - {{namespace}}-gateway
  http:
  - match:
    - uri:
        prefix: /minfo/
    route:
    - destination:
        host: movieinfo
        subset: v1
        port:
          number: 8080
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: moviebookui
        port:
          number: 80