---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: nginx-config
    namespace: {{namespace}}
    labels:
      app: moviebook
      component: proxy
  data:
    default.conf: |-
      server {
      listen 80 default_server;
      listen [::]:80 default_server ipv6only=on;

      server_name {{cube_host}};

      location / {
          resolver 8.8.8.8;
          proxy_ssl_session_reuse off;
          proxy_http_version 1.1;
          set $backend "https://{{cube_host}}";
          proxy_set_header Authorization "Bearer {{auth_token}}";
          proxy_pass_header Authorization;
          proxy_set_header Host {{cube_host}};
          proxy_pass $backend;
        }
      }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: {{namespace}}
  labels:
    app: moviebook
    component: proxy
spec:
  selector:
    matchLabels:
      component: proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: moviebook
        component: proxy
        namespace: moviebook-prod
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          name: nginx-config
          subPath: default.conf
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: "150Mi"
          requests:
            cpu: 100m
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config

---
apiVersion: v1
kind: Service
metadata:
  name: cube-proxy
  namespace: {{namespace}}
  labels:
    app: moviebook
    component: proxy
spec:
  ports:
  - port: 80
    name: http
  selector:
    component: proxy