##############
# External service
###############
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: aws-mysql-sakila
  namespace: {{namespace}}
  labels:
    app: moviebook
spec:
  hosts:
  - sakila2.cnt3lftdrpew.us-west-2.rds.amazonaws.com
  ports:
  - number: 3306
    name: mysql
    protocol: TCP
  resolution: DNS
  location: MESH_EXTERNAL
