auth_token = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJNZXNoREFnZW50VXNlckBudXRhbml4LmNvbSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJ0eXBlIjoicGF0IiwiY3VzdG9tZXJfaWQiOjEyMzMsImlhdCI6MTYwMjA1ODczOSwiZXhwIjoxOTE3NDE4NzM5fQ.C1q5Mrzc1L-JLk15Nf8tIfWUvbPCEPJmAT4aj_NsIkA"
customer = "Nutanix"
cube_application = "NutanixApp"
cube_instanceid = "test"
run_type = "Record"
recording_type = "Golden"