apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.cube.cubeDockerSecret}}
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
