---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cube
  namespace: {{ .Values.namespace }}
  labels:
    app: cube
spec:
  gateways:
  - {{ .Values.namespace }}-gateway
  hosts:
  - "{{ .Values.cube.host }}"
  http:
  - match:
    - uri:
        prefix: /api/
    route:
    - destination:
        host: cubeui-backend
        port:
          number: 8080
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: cubeui
        port:
          number: 80