apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: apachecxf
  namespace: {{namespace}}
spec:
  hosts:
  - "{{namespace_host}}"
  gateways:
  - {{namespace}}-gateway
  http:
  - match:
    - port: 8080
    route:
    - destination:
        host: apachecxf-record
        port:
          number: 8080
  - match:
    - port: 80
    route:
    - destination:
        host: apachecxf-replay
        port:
          number: 8080
