apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJhYWthc2hzaW5naGFsbWQwMSIsInBhc3N3b3JkIjoiV2VsY29tZUBtZCIsImVtYWlsIjoiYWFrYXNoLnNpbmdoYWxAbWVzaGR5bmFtaWNzLmlvIiwiYXV0aCI6IllXRnJZWE5vYzJsdVoyaGhiRzFrTURFNlYyVnNZMjl0WlVCdFpBPT0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: {{namespace}}
type: kubernetes.io/dockerconfigjson
