apiVersion: v1
kind: ConfigMap
metadata:
  name: cubews
  namespace: {{namespace}}
  labels:
    app: cube
data:
  APP_DOGFOOD: "{{cube_application}}"
  INSTANCE_DOGFOOD: "{{cube_instance}}"
  SERVICE_DOGFOOD: "{{cube_application}}"
  CUSTOMER_DOGFOOD: "{{customer}}"
  CUBE_RECORD_SERVICE: "{{record_host}}"
  REDIS_HOST: "redis.cache.svc.cluster.local"
  JAVA_OPTS: "-javaagent:/usr/local/tomcat/newrelic/newrelic.jar"
  NEW_RELIC_LOG: "STDOUT"
  SOLR_CORE: "{{solr_core}}"
  SOLR_BASE_URL: "{{solr_url}}"