apiVersion: v1
kind: ConfigMap
metadata:
  name: cubews
  namespace: {{namespace}}
data:
  APP_DOGFOOD: "Cube"
  INSTANCE_DOGFOOD: "prod"
  SERVICE_DOGFOOD: "Cube"
  CUSTOMER_DOGFOOD: "demo@cubecorp.io"