apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cubeui-backend-v1
  namespace: cube
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: cubeui-backend-v1
  targetCPUUtilizationPercentage: 60