---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: aws-solr
  namespace: {{namespace}}
  labels:
    app: cube
spec:
  hosts:
  - cubecorp.io #this is not used, but is required
  addresses:
  - 18.222.86.142/32
  ports:
  - number: 8983
    name: solr
    protocol: TCP
  resolution: NONE
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cubeservicestaging
  namespace: {{namespace}}
  labels:
    app: cube
spec:
  hosts:
  - {{staging_host}}
  ports:
  - number: 80
    name: cubeservice
    protocol: http
  resolution: DNS
  location: MESH_EXTERNAL

---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cubeservicedoogfooding
  namespace: {{namespace}}
  labels:
    app: cube
spec:
  hosts:
  - {{cube_host}}
  ports:
  - number: 80
    name: cubeservice
    protocol: http
  resolution: DNS
  location: MESH_EXTERNAL

---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: aws-rds-cubedb
  namespace: {{namespace}}
  labels:
    app: cube
spec:
  hosts:
  - cubeuibackend.cxg1ykcvrpg9.us-east-2.rds.amazonaws.com
  ports:
  - number: 5432
    name: psql
    protocol: TCP
  resolution: DNS
  location: MESH_EXTERNAL
