---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cube
  namespace: {{namespace}}
  labels:
    app: cube
spec:
  gateways:
  - {{namespace}}-gateway
  hosts:
  - "{{namespace_host}}"
  http:
  - match:
    - uri:
        prefix: /api/
    route:
    - destination:
        host: cubeui-backend
        port:
          number: 8080
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: cubeui
        port:
          number: 80

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cube
  namespace: {{namespace}}
  labels:
    app: cube
spec:
  gateways:
  - {{namespace}}-gateway
  hosts:
  - "{{namespace_host}}"
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: cubelogcollector
        port:
          number: 8080