name: Build Devtool

on:
  push:
    branches:
      - main
      - cubeui/build-test

  release:
    types: [published]

  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      version:
        description: 'version number of the build'
        required: true
        default: '1.0.0'

jobs:
  buildmacOS:
    name: Build devTool for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: git fetch --prune --unshallow --tags
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven(on PR)
        if: ${{ github.event_name == 'pull_request'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./build.sh
      - name: Build with Maven(release)
        if: ${{ github.event_name == 'release'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./build.sh
      - name: Build with Maven(publish internal)
        if: ${{ github.event_name == 'push'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./build.sh
      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE }}
          p12-password: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_PASSWORD }}
      - name: Build for macOS
        working-directory: ./ui
        if: ${{ github.event_name == 'push'}}
        env:
          APPLE_ID: ${{ secrets.AC_USERNAME }}
          APPLE_ID_PASSWORD: ${{ secrets.AC_PASSWORD }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version=$(git describe --tags `git rev-list --tags --max-count=1`)
          version=$(echo ${version} | awk -F. -v OFS=. '{$NF++;print}')
          TIMESTAMP=$(date "+%Y%m%d%H%M%S")
          BRANCH=${GITHUB_REF##*/}
          export RELEASE_TYPE=$BRANCH
          COMMIT=$(git rev-parse --short HEAD)
          NEXTVERSION="${version}-${BRANCH}.${TIMESTAMP}.${COMMIT}"
          echo $NEXTVERSION
          npm install
          brew install yq
          jq --arg version "${NEXTVERSION}" '.version = $version' package.json > "tmp" && mv "tmp" package.json
          yq eval '.extraResources += ["./bin/jdk-14.0.2+12-jre.tar.gz"]' -i electron-builder.main.yml
          cat electron-builder.main.yml
          npx webpack --mode production --display minimal --config webpack.electron.config.js
          npx electron-builder build -m --config electron-builder.main.yml
      - name: Build for macOS(release)
        working-directory: ./ui
        if: ${{ github.event_name == 'release'}}
        env:
          APPLE_ID: ${{ secrets.AC_USERNAME }}
          APPLE_ID_PASSWORD: ${{ secrets.AC_PASSWORD }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo $version
          npm install
          export RELEASE_TYPE=customer
          brew install yq
          jq --arg version "${version}" '.version = $version' package.json > "tmp" && mv "tmp" package.json
          yq eval '.extraResources += ["./bin/jdk-14.0.2+12-jre.tar.gz"]' -i electron-builder.yml
          npx webpack --mode production --display minimal --config webpack.electron.config.js
          npx electron-builder build -m --config electron-builder.yml --publish always
      - name: Build for macOS(manual)
        working-directory: ./ui
        if: ${{ github.event_name == 'workflow_dispatch'}}
        env:
          APPLE_ID: ${{ secrets.AC_USERNAME }}
          APPLE_ID_PASSWORD: ${{ secrets.AC_PASSWORD }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version=${{ github.event.inputs.version }}
          echo $version
          npm install
          export RELEASE_TYPE=customer
          brew install yq
          jq --arg version "${version}" '.version = $version' package.json > "tmp" && mv "tmp" package.json
          yq eval '.extraResources += ["./bin/jdk-14.0.2+12-jre.tar.gz"]' -i electron-builder.yml
          npx webpack --mode production --display minimal --config webpack.electron.config.js
          npx electron-builder build -m --config electron-builder.customer-fitch.yml --publish always

  buildlinux:
    name: Build devTool for linux
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - run: git fetch --prune --unshallow --tags
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven(on PR)
        if: ${{ github.event_name == 'pull_request'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./build.sh --buildDocker
      - name: Build with Maven(release)
        if: ${{ github.event_name == 'release'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "<settings><servers><server><id>github</id><username>x-access-token</username><password>${GITHUB_TOKEN}</password></server><server><id>docker.pkg.github.com</id><username>x-access-token</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
          ./build.sh -r=$version --buildDocker --deploy
      - name: Build with Maven(publish internal)
        if: ${{ github.event_name == 'push'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version=$(git describe --tags `git rev-list --tags --max-count=1`)
          IFS=$'\n'
          echo "<settings><servers><server><id>github</id><username>x-access-token</username><password>${GITHUB_TOKEN}</password></server><server><id>docker.pkg.github.com</id><username>x-access-token</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
          NEXTVERSION=$(echo ${version} | awk -F. -v OFS=. '{$NF++;print}')
          git tag $NEXTVERSION
          git push --tags
          ./build.sh -r=$NEXTVERSION
          
      - name: Build for linux
        working-directory: ./ui
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.event_name == 'push'}}
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.6.0/yq_linux_386 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
          version=$(git describe --tags `git rev-list --tags --max-count=1`)
          version=$(echo ${version} | awk -F. -v OFS=. '{$NF++;print}')
          TIMESTAMP=$(date "+%Y%m%d%H%M%S")
          BRANCH=${GITHUB_REF##*/}
          export RELEASE_TYPE=$BRANCH
          COMMIT=$(git rev-parse --short HEAD)
          NEXTVERSION="${version}-${BRANCH}.${TIMESTAMP}.${COMMIT}"
          sudo apt-get update -y
          sudo apt-get install wine64 -y
          npm install
          jq --arg version "${NEXTVERSION}" '.version = $version' package.json > "tmp" && mv "tmp" package.json
          /usr/bin/yq eval '.extraResources += ["./bin/OpenJDK14U-jre_x64_linux_openj9_14.0.2_12_openj9-0.21.0.tar.gz"]' -i electron-builder.main.yml
          npx webpack --mode production --display minimal --config webpack.electron.config.js
          npx electron-builder build -l --config electron-builder.main.yml

      - name: Build for linux(release)
        working-directory: ./ui
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.event_name == 'release'}}
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.6.0/yq_linux_386 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
          version=$(git describe --tags `git rev-list --tags --max-count=1`)
          npm install
          export RELEASE_TYPE=customer
          jq --arg version "${version}" '.version = $version' package.json > "tmp" && mv "tmp" package.json
          /usr/bin/yq eval '.extraResources += ["./bin/OpenJDK14U-jre_x64_linux_openj9_14.0.2_12_openj9-0.21.0.tar.gz"]' -i electron-builder.yml
          npx webpack --mode production --display minimal --config webpack.electron.config.js
          npx electron-builder build -l --config electron-builder.yml --publish always

  buildwindows:
    name: Build devTool for windows
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - run: git fetch --prune --unshallow --tags
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven(on PR)
        shell: bash
        if: ${{ github.event_name == 'pull_request'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./build.sh
      - name: Build with Maven(release)
        shell: bash
        if: ${{ github.event_name == 'release'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./build.sh
      - name: Build with Maven(publish internal)
        shell: bash
        if: ${{ github.event_name == 'push'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./build.sh
      - name: Build for windows
        shell: pwsh
        working-directory: .\ui
        if: ${{ github.event_name == 'push'}}
        env:
          WIN_CSC_LINK: ${{ secrets.WIN_CSC_LINK }}
          WIN_CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          choco install yq --version 3.4.1 -y
          echo 'Decoding certificate string'
          $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.WIN_CSC_LINK }}")
          [IO.File]::WriteAllBytes("md-cert.pfx", $pfx_cert_byte)
          npm install
          $revision = $(git rev-list --tags --max-count=1)
          $version = $(git describe --tags $revision)
          $versionParts = $version.split('.')
          ([int]$versionParts[2])++
          $NEW_VERSION_NUMBER = $versionParts -join('.')
          $TIMESTAMP = [long] (Get-Date -Date ((Get-Date).ToUniversalTime()) -UFormat %s)
          $COMMIT = $(git rev-parse --short HEAD)
          $BRANCH = $(git branch --show-current).split("/")[-1]
          $Env:RELEASE_TYPE = $BRANCH
          $NEXT_VERSION = "$NEW_VERSION_NUMBER-$BRANCH.$TIMESTAMP.$COMMIT"
          echo $NEXT_VERSION
          jq --arg version $NEXT_VERSION '.version = $version' package.json > .\tmp.txt
          $CONTENT = Get-Content -Path .\tmp.txt
          Remove-Item -path .\package.json
          Add-Content -Path .\package.json -Value $CONTENT
          # yq w .\electron-builder.main.yml win.certificateFile md-cert.pfx |  yq w - win.certificatePassword "${{ secrets.WIN_CSC_KEY_PASSWORD }}" | yq w - extraResources[5] "./bin/OpenJDK14U-jre_x64_windows_openj9_14.0.2_12_openj9-0.21.0.zip" > ebtmp.txt
          yq w .\electron-builder.main.yml extraResources[5] "./bin/OpenJDK14U-jre_x64_windows_openj9_14.0.2_12_openj9-0.21.0.zip" > ebtmp.txt
          $BUILDER_CONTENT = Get-Content -Path .\ebtmp.txt
          echo $BUILDER_CONTENT
          Remove-Item -path .\electron-builder.main.yml
          Add-Content -Path .\electron-builder.main.yml -Value $BUILDER_CONTENT
          npx webpack --mode production --display minimal --config webpack.electron.config.js
          npx electron-builder build -w --config electron-builder.main.yml

      - name: Build for windows(release)
        working-directory: .\ui
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.event_name == 'release'}}
        run: |
          choco install yq --version 3.4.1 -y
          echo 'Decoding certificate string'
          $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.WIN_CSC_LINK }}")
          [IO.File]::WriteAllBytes("md-cert.pfx", $pfx_cert_byte)
          npm install
          $revision = $(git rev-list --tags --max-count=1)
          $version = $(git describe --tags $revision)
          jq --arg version $version '.version = $version' package.json > .\tmp.txt
          $CONTENT = Get-Content -Path .\tmp.txt
          Remove-Item -path .\package.json
          Add-Content -Path .\package.json -Value $CONTENT
          $Env:RELEASE_TYPE = "customer"
          # yq w .\electron-builder.yml win.certificateFile md-cert.pfx |  yq w - win.certificatePassword "${{ secrets.WIN_CSC_KEY_PASSWORD }}" | yq w - extraResources[5] "./bin/OpenJDK14U-jre_x64_windows_openj9_14.0.2_12_openj9-0.21.0.zip"> .\ebtmp.txt
          yq w .\electron-builder.main.yml extraResources[5] "./bin/OpenJDK14U-jre_x64_windows_openj9_14.0.2_12_openj9-0.21.0.zip" > ebtmp.txt
          $BUILDER_CONTENT = Get-Content -Path .\ebtmp.txt
          echo $BUILDER_CONTENT
          Remove-Item -path .\electron-builder.yml
          Add-Content -Path .\electron-builder.yml -Value $BUILDER_CONTENT
          npx webpack --mode production --display minimal --config webpack.electron.config.js
          npx electron-builder build -w --config electron-builder.yml --publish always