name: Docker Image CI

on:
  push:
    branches: develop
  pull_request:
    branches: develop

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: cubeiocorp/kubectl
        tags: latest
