name: Docker Image CI

on:
  push:
    branches: develop
  pull_request:
    branches: develop

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    ‐ name: build
      id: build
      uses: docker/build-action@v1
      with:
        repository: cubeiocorp/kubectl
        tags: latest
    ‐ name: login
      uses: docker/login-action@v1
      with:
        registry: cubeiocorp/kubectl
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    ‐ name: push
      uses: docker/push-action@v1
      with:
        registry: cubeiocorp/kubectl
        tags: ${{ outputs.build.tags }}
